POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "username": "Binh Bong",
    "password": "12345678"
}


###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "username": "Binh Bong",
    "password": "12345678"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWVlMmViMzEzMTE3OTI3NjQ4MmMwNzEiLCJpYXQiOjE2NDI5OTk1Njd9.GvgzJV3kN88jJy4xUKUFgjRcicDQUTKSMC9hmKZrBbU

{
    "title": "This is a famous building",
    "description": "a place is very interested in",
    "url": "lazada.com",
    "status":"LEARNED"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWVlMmViMzEzMTE3OTI3NjQ4MmMwNzEiLCJpYXQiOjE2NDI5OTk1Njd9.GvgzJV3kN88jJy4xUKUFgjRcicDQUTKSMC9hmKZrBbU

###
PUT http://localhost:5000/api/posts/61ee2f2d131179276482c072
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWVlMmViMzEzMTE3OTI3NjQ4MmMwNzEiLCJpYXQiOjE2NDI5OTk1Njd9.GvgzJV3kN88jJy4xUKUFgjRcicDQUTKSMC9hmKZrBbU

{
    "title": "This is a famous building update",
    "description": "Nodejs",
    "url": "shoope.com",
    "status": "LEARNING"
}

###
DELETE  http://localhost:5000/api/posts/61ee2f2d131179276482c072
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWVlMmViMzEzMTE3OTI3NjQ4MmMwNzEiLCJpYXQiOjE2NDI5OTk1Njd9.GvgzJV3kN88jJy4xUKUFgjRcicDQUTKSMC9hmKZrBbU
